library(ggplot2)
library(Cairo)
library(ggthemes)

Mechanism = c("MCMv3.2", "MCMv3.1", "MOZART-4", "MOZART-4", "MOZART-4", "MOZART-4", "RADM2", "RADM2", "RACM", "RACM", "RACM", "RACM2", "RACM2", "RACM2", "RACM2", "RACM2")
Product = c("C5", "C5", "C4", "C3", "C2", "C1", "C4", "C2", "C4", "C2", "C1", "C5", "C4", "C3", "C2", "C1")
Reactant = c(5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5.6, 5.6, 5.6, 5.6, 5.6)
Ratio = c(5, 5, 3, 1.05, 0.8, 0.1, 3.003, 0.912, 3.023, 0.6024, 0.052, 0.039, 0.169, 0.692, 0.276, 0.069)
data = data.frame(Mechanism, Reactant, Product, Ratio)

data$Mechanism = factor(data$Mechanism, levels = c("MCMv3.2", "MCMv3.1", "MOZART-4", "RADM2", "RACM", "RACM2"))
data$Product = factor(data$Product, levels = c("C5", "C4", "C3", "C2", "C1"))
my.colours = c("C5" = "#2b9eb3", "C4" = "#ef6638", "C3" = "#0e5628", "C2" = "#f9c500", "C1" = "#6c254f")

plot = ggplot(data, aes(x = Mechanism, y = Ratio, fill = Product))
plot = plot + geom_bar(stat = "identity")
plot = plot + geom_point(aes(y = Reactant), show_guide = FALSE)
plot = plot + scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 1), expand = c(0, 0))
plot = plot + scale_x_discrete(expand = c(0, 0))
plot = plot + scale_fill_manual(values = my.colours, guide = guide_legend(direction = "horizontal"), limits = rev(levels(data$Product)))
plot = plot + ylab("Reactive Carbon")
plot = plot + theme_tufte()
plot = plot + theme(legend.title = element_blank())
plot = plot + theme(axis.title.x = element_blank())
plot = plot + theme(axis.ticks.x = element_blank())
plot = plot + theme(axis.line = element_line(colour = "black"))
plot = plot + theme(axis.title = element_text(size = 13, face = "bold"))
plot = plot + theme(axis.text.x = element_text(size = 13, face = "bold"))
#plot = plot + theme(axis.text.x = element_text(size = 13, face = "bold", angle = 45, hjust = 0.7, vjust = 0.8))
plot = plot + theme(legend.text = element_text(size = 11))
plot = plot + theme(axis.text.y = element_text(size = 11))
plot = plot + theme(legend.position = c(0.5, 0.95))

CairoPDF(file = "HC5P_NO_C_numbers.pdf", width = 8.6, height = 6)
print(plot)
dev.off()
